web/src/main/java/org/fao/geonet/kernel/SingleThesaurusFinder.java
web/src/main/java/org/fao/geonet/kernel/Thesaurus.java
web/src/main/java/org/fao/geonet/kernel/ThesaurusFinder.java
web/src/main/java/org/fao/geonet/kernel/search/ConfigLoader.java
web/src/main/java/org/fao/geonet/kernel/search/classifier/BroaderTerm.java
web/src/main/java/org/fao/geonet/kernel/search/classifier/ClassificationScheme.java
web/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordRelation.java
web/src/main/webapp/WEB-INF/config-summary.xml
web/src/test/java/org/fao/geonet/kernel/search/ConfigLoaderTest.java
web/src/test/java/org/fao/geonet/kernel/search/KeywordsSearcherTest.java
web/src/test/java/org/fao/geonet/kernel/search/classifier/BroaderTermTest.java
web/src/test/java/org/fao/geonet/kernel/search/classifier/ClassificationSchemeTest.java
web/src/test/java/org/fao/geonet/test/CategoryTestHelper.java
web/src/test/java/org/fao/geonet/test/ThesaurusDirectoryLoader.java
web/src/test/resources/thesauri/classificationScheme.rdf
web/src/test/resources/thesauri/vocabulary.rdf

which creates category paths to be indexed for facetted searching by looking up the parent categories for terms defined in a vocabulary thesaurus
in a classification scheme thesaurus

Change broader term classifier to a classification scheme classifier

---

web/src/main/webapp/WEB-INF/config-summary.xml

OK, enabled indexing of deep facets but didn't up limit on levels returned.
Up to 10 to let indexing decide what's returned

Display all facets indexed

---

web/src/main/java/org/fao/geonet/GeonetContext.java
web/src/main/java/org/fao/geonet/Geonetwork.java
web/src/main/java/org/fao/geonet/constants/Geonet.java
web/src/main/java/org/fao/geonet/kernel/search/CollectionAvailabilityFilter.java
web/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
web/src/main/java/org/fao/geonet/kernel/search/UserQueryInput.java
web/src/main/java/org/fao/geonet/monitor/link/CheckInfo.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerDefault.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerInterface.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerUtils.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerWfs.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerWms.java
web/src/main/java/org/fao/geonet/monitor/link/LinkInfo.java
web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorInterface.java
web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorService.java
web/src/main/java/org/fao/geonet/monitor/link/MetadataRecordInfo.java
web/src/main/java/org/fao/geonet/services/util/SearchDefaults.java
web/src/main/webapp/WEB-INF/config.xml
web/src/test/java/org/fao/geonet/monitor/link/LinkInfoTest.java
web/src/test/java/org/fao/geonet/monitor/link/MetadataRecordInfoTest.java

* Core logic (and interface)
* Unit tests

Link Monitor

---

web/src/main/java/org/fao/geonet/Geonetwork.java
web/src/main/java/org/fao/geonet/monitor/link/CheckInfo.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerDefault.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerInterface.java
web/src/main/java/org/fao/geonet/monitor/link/LinkCheckerUtils.java
web/src/main/java/org/fao/geonet/monitor/link/LinkInfo.java
web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorInterface.java
web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorService.java
web/src/main/java/org/fao/geonet/monitor/link/MetadataRecordInfo.java
web/src/main/webapp/WEB-INF/classes/JZkitApplicationContext.xml
web/src/main/webapp/WEB-INF/config.xml

Refactor the LinkMonitor. Main change here is using dependency injection instead of reflections - this is the "java" way.

2.10.x imos link monitor tweaks

---

web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorService.java
web/src/main/java/org/fao/geonet/monitor/link/MetadataRecordInfo.java

If a record was updated, enable LinkMonitorService to find out about
it and update the record (with new links and such)

LinkMonitorService Supports updating of records

---

web/src/main/java/org/fao/geonet/monitor/link/LinkInfo.java
web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorService.java
web/src/test/java/org/fao/geonet/monitor/link/LinkInfoTest.java

I am just trying to get GeoNetwork running with my changes to see them in action.

Updated GeoNetwork link monitor algorithm

---

web/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
web/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
web/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
web/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
web/src/main/webapp/scripts/harvesting/csw/model.js
web/src/main/webapp/scripts/harvesting/csw/view.js
web/src/main/webapp/xsl/harvesting/csw/csw.xsl
web/src/main/webapp/xsl/xml/harvesting/csw.xsl

Already available in GeoNetwork 3.0.

Add transform option to CSW harvester

---

web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWps.java
web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceMonitorService.java
web/src/main/webapp/WEB-INF/config.xml

[#76](https://github.com/aodn/issues/issues/76)

Added WPS timeout config

---

web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWfs.java
web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWms.java
web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWmsFilters.java
web/src/main/webapp/WEB-INF/classes/JZkitApplicationContext.xml

For https://github.com/aodn/backlog/issues/668

Online resources check filters

---

web/src/main/java/org/fao/geonet/monitor/onlineresource/MetadataRecordInfo.java
web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerUtils.java
web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWfs.java

Fixes https://github.com/aodn/issues/issues/114.
Provide more info for specific failure types

Return a fail on WFS GF check URL exception

---

web/src/main/webapp/WEB-INF/classes/JZkitApplicationContext.xml

Disable WPS resource checker, since it doesn't work with AWS-WPS

---

web/src/main/webapp/WEB-INF/log4j.cfg

Fixes https://github.com/aodn/issues/issues/208

Log4j Size based geonetwork.log rotation 

---

oaipmh/src/main/java/org/fao/oaipmh/requests/Transport.java

fixed issue https://github.com/aodn/issues/issues/301

fixes https issue for oai-pmh harvester

---

web/src/main/java/au/org/emii/classifier/AodnTerm.java
web/src/main/java/au/org/emii/classifier/AodnTermResultInterpreter.java
web/src/main/java/au/org/emii/classifier/AodnThesaurus.java
web/src/test/java/au/org/emii/classifier/LabelClassifierTest.java
web/src/test/resources/thesauri/vocabulary.rdf

Use altLabel if present in preference to prefLabel
Only ignore replaced terms when looking up term using label.

Address Natalia's review comments

---

web/src/main/java/au/org/emii/classifier/AodnTermClassifier.java

After discussion with Seb and Nat they will use displayLabel to specify a different label for the portal.

Don't use altLabel in preference to prefLabel

---

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl
web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/process/add-collection-config.xsl

and add indexing of platforms/parameters and organisational units to the iso19139 indexing stylesheet
e4578e2

Add iso19139 transform to add collection config to incoming iso19139 records

---

web/src/main/java/org/fao/geonet/csw/common/requests/CatalogRequest.java

Since these messages weren't going through the logger, they appeared to be a part of which ever message had been logged just before them grrr

Comment out some POS system.out.printlns

---

web/src/main/webapp/scripts/core/kernel/kernel.js

This is temporary hack to be used until we retire our use of geonetwork 2

using direct xhr requests to get the required sources and groups from geonetwork 3

---

web/src/main/java/org/fao/geonet/kernel/mef/MEFVisitor.java

Need to define block for if statement if multiple statements included

---

web/src/main/java/org/fao/geonet/util/GmlWktConverter.java
web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl

For 19115-3 records harvested as 19139 records from GN3

Index bounding polygons

---

jeeves/pom.xml
pom.xml
web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl

Index creative commons details in 19139 records mapped from 19115-3 records in GN3

Fixes aodn/backlog#1740

---

web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
web/src/main/java/org/fao/geonet/kernel/mef/MEFVisitor.java

https://github.com/aodn/issues/issues/816

Allow GN2 to harvest iso19115-3 original recipe records
