web/src/main/java/org/fao/geonet/kernel/search/CollectionAvailabilityFilter.java, web/src/main/java/org/fao/geonet/monitor/link/LinkInfo.java, web/src/main/java/org/fao/geonet/monitor/link/LinkMonitorService.java, web/src/test/java/org/fao/geonet/monitor/link/LinkInfoTest.java
As per @pblain 's request. Algorithm for determining `UNKNOWN`, `FAILED`, `WORKING` has slightly changed. Best if you look at the modified source without the diff:
https://github.com/aodn/core-geonetwork/blob/2.10.x-imos-link-monitor-alg-change/web/src/main/java/org/fao/geonet/monitor/link/LinkInfo.java#L47
In a nutshell, it's much simpler since don't return `UNKNOWN` if there are not enough checks, we calculate anyway and compare to `percentWorking`.
=> 2.10.x imos link monitor alg change

web/src/main/webapp/WEB-INF/config-lucene.xml
The portal citation-feature needs additional citation-related attributes
available, such as usage limitations and licensing information.  Some of
these are already exposed, but all under the generic Constraints
tagname.  We repeat these here so as not to break current consumers of
that tag, using distinct tag names each.
This will also require an update to the schema plugins (aodn/schema-plugins#17)
=> Expose additional citation fields in summary

web/src/main/java/org/fao/geonet/kernel/search/facet/DimensionFormatter.java, web/src/test/java/org/fao/geonet/kernel/search/facet/DimensionFormatterTest.java
Display codes for temporal resolution for now.  Enable display of translated values later
Fixes issue where clicking on the facet value didn't find any records
=> Display temporal resolution codes for facet values

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl
The // here was picking up all constraints including metadata constraints for each gmd:resourceConstraints in the metadata.
=> Only index resource constraints and only index each one once.

web/src/main/webapp/WEB-INF/config-lucene.xml
Depends on aodn/schema-plugins#31
Licence metadata often includes a link to an image logo, which we can use to display in the portal's download-confirmation window.
=> Add imageLink to lucene dumpFields

jeeves/src/main/java/jeeves/utils/XmlRequest.java
Have hard coded timeout values here in our custom version of GeoNetwork.
Timeouts need to be configurable when fitting this to GeoNetwork 3.0.  Its not worth doing it here as it would need to be rewritten when fitting to Geonetwork 3.0.
=> Add default connection and read timeout to http requests

web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWmsFilters.java, web/src/main/webapp/WEB-INF/classes/JZkitApplicationContext.xml
If the new onlineResource of `AODN:FILTERS--enabled` is present in a metadata record, then there is the expectation that there must be one or more filter that can be checked.
=> Online resources check filters new requirements

web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceMonitorService.java
Deleting a record effectively stopped any online resource checking from happening as reindexing
then failed everytime it tried to lookup the title on the missing record in the index.
Use the title from the previously stored information for the record used to identify that the record
has been deleted instead.
=> Fixes aodn/issues#124

web/src/main/java/org/fao/geonet/monitor/onlineresource/CheckInfo.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/CheckResult.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/MetadataRecordInfo.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerDefault.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerInterface.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerUtils.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWfs.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWmsFilters.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWmsGetCapabilities.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceCheckerWps.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceInfo.java, web/src/test/java/org/fao/geonet/monitor/onlineresource/OnlineResourceInfoTest.java
Changed CheckInfo to pass back a CheckResult instead of a boolean to indicate the success/failure of the check.  CheckResult has a resultReason field which can be used to pass back the error message if the check fails.  All resultReasons for failed checks are logged when the state of the collection changes to FAILED.
=> Issue637 fix

web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceMonitorService.java
ORM is a  ScheduledExecutorService
If any execution of the task encounters an exception, subsequent executions are suppressed. Otherwise, the task will only terminate via cancellation or termination of the executor.
This will catch exceptions and thus allow the ORM to restart next time around.  We may modify this again later once we understand what exception is being thrown that occaisionally stops the ORM.
=> catch all exceptions in ORM and log

web/src/main/java/org/fao/geonet/Geonetwork.java, web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceMonitorService.java
See: https://www.cosmocode.de/en/blog/schoenborn/2009-12/17-uncaught-exceptions-in-scheduled-tasks
Note that future.get() blocks the thread it runs in until an exception occurs (or ORM stops - which should be never)
=> Use scheduled future

web/src/main/java/au/org/emii/classifier/UriLabelClassifier.java, web/src/main/webapp/WEB-INF/config-summary.xml, web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl, web/src/test/java/au/org/emii/classifier/LabelClassifierTest.java, web/src/test/java/au/org/emii/classifier/UriClassifierTest.java, web/src/test/java/au/org/emii/classifier/UriLabelClassifierTest.java
Indexes the keywords `platformKeyword` and `parameterKeyword` from 19115-3 records and alters the config to use these keywords as in index in lieu of the original `parameterUri` and `platformUri`. 
The introduction of a new `UriLabelClassifier`, which acts as a proxy for either a URI or a prefLabel, allows backward compatibility with existing harvesting methods that include adding a URI to the metadata.
=> Update the Geonetwork 2.10 19139 schema plugin to index 19115-3 records

web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
When using a GeoNetwork 2 instance to harvest from a GeoNetwork 3 instance a series of invalid XML errors occur due to the change in the formatting of the language type. GN3 appears to only allow a 3 character representation of the language however GN2 allows either 2 or 3 character representations.
The hierarchical structure of the groups also appears to have different tiers, possibly an issue with GN3 however its easiest to resolve the issue from our fork of GN2.
This fix is required for the PR https://github.com/aodn/aodn-portal/pull/2837 to function correctly.
=> Update harvester for GN3

web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, web/src/main/java/org/fao/geonet/kernel/mef/MEFVisitor.java
19115-3.2018 records always contain an iso19139 version. The default behaviour of GN2 is to reject the record as the 19115-3 schema is not recognised. This update adds the ability to search the harvested zip archive for the 19139 version of the record and use that in its place.
[Backlog Item #1508](https://github.com/aodn/backlog/issues/1508)
=> Update GN2 to harvest 19139 records that are packaged with 19115-3.2018 records

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/process/linkage-updater.xsl, web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/process/systest-catalogue-imos-harvest.xsl, web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/process/transform_testing_urls.xsl
Add specific transform for converting catalogue-imos url's to systest url's.
Also add normal linkage-updater and transform_testing_urls transforms for catalogue-portal harvesting and normal systest harvesting after the upgrade.
Example gridded and non-gridded output of records transformed using systest-catalogue-imos-harvest.xsl:
[acorn.txt](https://github.com/aodn/core-geonetwork/files/4762763/acorn.txt)
[argo.txt](https://github.com/aodn/core-geonetwork/files/4762764/argo.txt)
Example gridded and non-gridded output performed locally using linkage-updater:
[acorn-portal.txt](https://github.com/aodn/core-geonetwork/files/4762768/acorn-portal.txt)
[argo-portal.txt](https://github.com/aodn/core-geonetwork/files/4762769/argo-portal.txt)
Example gridded and non-gridded output of above …
=> Fixes aodn/backlog#1783

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl
records by GN3 when harvested by GN2.
* Index layer name for use by aws-wps (also required for aodn/backlog#1783)
* Remove duplicate indexing of organisation name - fixes aodn/backlog#1784
* Index AODN Organisation Vocabulary keywords so that IMOS facilities/sub facilities etc are included in the organisation facet
=> Fix various indexing issues with 19115-3:2018 records converted to 19139

web/src/main/java/org/fao/geonet/monitor/onlineresource/OnlineResourceMonitorService.java
Fix ConcurrentModificationException when reindexing metadata after a record has been deleted.
You can't remove an item from a HashMap while you are iterating over it unless you use an iterator.
An exception thrown here stops online resource checks being performed.
Note that records are only ever marked as deleted on the lucene index and so are still included by the online resource monitor when reindexing its internal index.   Only rebuilding the lucene index actually removes the record, which is why this was happening only when running the config-manager script which kicks off a index rebuild after records had been deleted by the harvester.
=> Fixes aodn/issues#441

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl
Handle new method of namespacing gml3.2 used in 19115-3:2018 and later versions of 19139 when indexing the temporal extent
New namespace is used when converting 19115-3:2018 records to 19139 records in GN3.
=> Fixes aodn/backlog#1788

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl
The license link is not included when converting 19115-3:2018 records to 19139
Map the license link from the license name which is included
Only required until we upgrade catalogue-portal to GN3 as then we'll get the full 19115-3:2018 record
=> Fixes aodn/backlog#1781

jeeves/src/main/java/jeeves/utils/Xml.java, web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/extract-gml.xsl
Handle gml/3.2 namespacing of gml 3.2 bounding polygon's used by 19139 records harvested from GN3 as well as gml namespacing when indexing spatial extents.
=> Fixes aodn/backlog#1798

web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/process/systest-catalogue-imos-harvest.xsl
Redirect attachment downloads to catalogue-imos.prod.aodn.org.au until catalogue-imos is upgraded.
=> Fixes aodn/backlog#1795

web/src/main/java/org/fao/geonet/monitor/onlineresource/MetadataRecordInfo.java
Define gmd namespace used in xpath expression so evaluation doesn't rely on how its defined in the source element.
=> Fixes aodn/issues#654
